RedisGears/RedisGears

src/execution_plan.c, src/execution_plan.h
Each execution step is corresponding to an action.
Each action return ActionResult that indicate whether or not to continue
or stop the execution. In addition each action is responsible to switch
to another state if needed.
=> Change Execution Plan to work as a state machine

src/GearsBuilder.py, src/execution_plan.c, src/execution_plan.h, src/keys_reader.c, src/keys_reader.h, src/module.c, src/redisgears.h, src/redisgears_python.c
1. if setting MaxExecutions to 0, no execution will be deleted automatically.
2. Events to execution are sent via a linked list and not with libevent to prevent deadlock
3. Keys only reader is now implemented in C to increase performance, in addition, if exect match (no prefix)
is requested then 'scan' command will not be used.
=> Changed the following:

.dockerignore, Dockerfile, Makefile, build/platforms/Makefile, pytest/test_basics.py, system-setup.py
Performs Docker builds for supported platforms via:
make -C build/platforms <<platform-name>>
Supported platforms are shown by:
make -C build/platforms platforms
=> Added platforms build facility

pytest/test_basics.py, src/GearsBuilder.py, src/execution_plan.c, src/record.c, src/record.h, src/redisgears_python.c, src/redisgears_python.h
Sometime you need to execute a block of code and make sure not other commands will
run in between, 'with atomic()' allows you to do it.
example:
```
with atomic():
execute(...)
execute(...)
execute(...)
```
=> added 'with atomic()' to allow atomic execution of python code.

recipes/cluster/Dockerfile, recipes/cluster/README.md, recipes/cluster/create-cluster, recipes/cluster/docker-config.sh, recipes/cluster/docker-entrypoint.sh
Pretty cool stuff:
```
$ docker build -t rgcluster . && docker run -it --rm --name rgcluster -p 30001:30001  -p 30002:30002 -p 30003:303  rgcluster
Sending build context to Docker daemon  11.78kB
Step 1/7 : FROM redislabs/redisgears:latest
---> ab5dab76312f
Step 2/7 : WORKDIR /cluster
---> Using cache
---> 12fb7f4417ca
Step 3/7 : COPY create-cluster .
---> Using cache
---> ab5e4a407628
Step 4/7 : COPY docker-config.sh .
---> Using cache
---> 7b74870248cd
Step 5/7 : COPY docker-entrypoint.sh /usr/local/bin
---> Using cache
---> ea6509f9957a
Step 6/7 : EXPOSE 30001-30006
---> Using cache
---> b865e362b5f8
Step 7/7 : CMD []
---> Using cache
---> 33f65377eced
Successfully built 33f65377eced
Successfully tagged rgcluster:latest
Starting 30001
Starting 30002
Starting 30003
>>> Performing hash …
```
=> Adds rgcluster docker

Makefile, pytest/test_basics.py, pytest/test_errors.py, pytest/test_register.py, ramp.yml, src/GearsBuilder.py, src/commands.c, src/commands.h, src/config.c, src/config.h, src/execution_plan.c, src/execution_plan.h, src/mgmt.c, src/mgmt.h, src/module.c, src/readers/command_reader.c, src/readers/command_reader.h, src/readers/keys_reader.c, src/readers/shardid_reader.c, src/readers/shardid_reader.h, src/readers/streams_reader.c, src/redisgears.h, src/redisgears_python.c, src/redisgears_python.h, src/utils/thpool.c, src/utils/thpool.h
1. We have a thread pull for execution run
2. It is possible to define a virtual worker.
Execution on same worker will not run in parallel.
Registrations use it to force execution order.
Other execution run on their own worker, i.e, no execution order is prommised.
=> Added thread pull support to run execution

docs/examples.md, docs/snippets/examples/automatic-expire.py, docs/snippets/runtime/configget.py, docs/snippets/runtime/gearsconfigget.py, docs/snippets/test_snippets.py, src/GearsBuilder.py
When calling gearsConfigGet the warning gets printed.
Also, updates docs API snippets so these use the non-deprecated config methods and adds an example for automatically expiring keys.
=> Fixes a false deprecation warning

Dockerfile, Dockerfile.arm
@rafie I think these should use :latest, for your consideration
=> Bumps Redis version in docker images to 5.0.8

src/redisgears_python.c
When calling: `redisAI.createTensorFromValues('FLOAT', [1, 3], [0, 1, 2])`, RedisGear is throwing error:
```
'spam.error: values argument must be iterable\n'
```
This is due to the `PyIter_Check` that is being removed in this PR, rather we are checking whether the iterator is NULL like the rest of the places.
> `PyIter_Check` is for checking whether an object **is** an iterator, not whether it can *provide* one. ([ref](https://stackoverflow.com/a/59145186/4135289))
=> Remove PyIter_Check in createTensorFromValues

src/commands.c
Drop execution returns an error with wrong spelling. Fixed that.
=> Fix spelling: "exits" -> "exist"

system-setup.py
package may exist because last install.  Add `--replacepkgs ` and try to reinstall the package if package has already install otherwise self.run will return exceptions.  
```
$sudo rpm -Uv /tmp/epel-release-latest-7.noarch.rpm
warning: /tmp/epel-release-latest-7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
warning: Unable to get systemd shutdown inhibition lock: Unit is masked.
Preparing packages...
package epel-release-7-12.noarch is already installed
[011158133251 /home/code/RedisGears]
$echo $?
1
```
```
$sudo rpm -Uv /tmp/epel-release-latest-7.noarch.rpm --force
warning: /tmp/epel-release-latest-7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
warning: Unable to get systemd shutdown inhibition lock: Unit is masked.
Preparing packages... …
```
=> Fix: fix epel install failure

pytest/test_network.py, src/cluster.c, src/cluster.h, src/commands.c, src/common.h, src/execution_plan.c, src/module.c, src/readers/command_reader.c, src/redisgears_python.c
1. The following is not allow if cluster is not yet initalized:
* RG.PYEXECUTE
* RG.DROPEXECUTION
* RG.ABORTEXECUTION
* RG.UNREGISTER
2. Import python requirement will not be allowed if cluster is not yet initalized.
3. RG.TRIGGER that triggered distributed execution will return error if cluster
is not yet initalized.
4. Key space notification that trigger a distributed execution will failed.
5. A shard that did not yet recieve the cluster topology will send 'ERRCLUSTER'
error, a shard that gets this error will send the cluster topology to the
other shard so the cluster will get back to functional state faster
and we will be able to continue running executions.
6. hashtag() function will use RedisModule_ShardingGetSlotRange RedisModule API
(if available) to not be depends on ClusterSet …
=> Better Redis-Enterprise cluster integration

pytest/test_network.py, src/cluster.c, src/cluster.h, src/commands.c, src/common.h, src/execution_plan.c, src/module.c, src/readers/command_reader.c, src/redisgears_python.c
* Better Redis-Enterprise cluster intergration
1. The following is not allow if cluster is not yet initalized:
* RG.PYEXECUTE
* RG.DROPEXECUTION
* RG.ABORTEXECUTION
* RG.UNREGISTER
2. Import python requirement will not be allowed if cluster is not yet initalized.
3. RG.TRIGGER that triggered distributed execution will return error if cluster
is not yet initalized.
4. Key space notification that trigger a distributed execution will failed.
5. A shard that did not yet recieve the cluster topology will send 'ERRCLUSTER'
error, a shard that gets this error will send the cluster topology to the
other shard so the cluster will get back to functional state faster
and we will be able to continue running executions.
6. hashtag() function will use RedisModule_ShardingGetSlotRange RedisModule API …
=> Better Redis-Enterprise cluster integration (#431)

plugins/python/redisai.h, plugins/python/redisgears_python.c, pytest/test_basics.py
Add a new DAGRunner py object type and create its methods that use for building a DAG. Enable to create a DAG and run it asynchronously in RedisAI.
=> Support DAG run in RedisAI through python plugin

src/redisgears_python.c
* update python interpreter version to 3.7.12
* python allocator will return 16-byte aligned addresses
(cherry picked from commit 834893e71fbaa1f8ff928c76f2dd3fc0724abc8e)
=> update python interpreter version to 3.7.12 (#624)

docs/requirements.txt
After this github action error: https://github.com/RedisGears/RedisGears/runs/4234637668?check_suite_focus=true
Try to solve this based on: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest
=> Upgrade pytest version to 6.2.5

docs/index.md, mkdocs.yml
After uploading RedisAI docs, I noticed that it is not accessible from the website. This PR should address this.
=> Add redisai docs to nav bar and home page

pytest/test_register.py, src/cluster.c, src/readers/streams_reader.c
On oss cluster, if cluster is not initialized, read commands will failed and return an error. On stream reader, we assert that we read the stream successfully, such assertion will failed on uninitialized cluster and will cause a crash.
Solution:
1. Before start scaning for streams, wait for cluster to be initialized.
2. '1' is not enough, by the time we find a stream to read the cluster might get uninitialized again. To solve this, if we failed to read    the stream we retry after 5 seconds. We retry up to 10 times and than abort.
todo:
=> Fix #558, wait for cluster to be initialized when reading stream data

leakcheck.supp, src/module.c
1. Fix wrong valgrind error when writing pointer address to pipe. Valgrind might think we lost the pointer if the processes exit before reading it from the pipe. Added this case to suppression file.
2. Use shutdown event to do cleanup instead of __attribute__((destructor)) This way we know that we run when the GIL help and there will be no race conditions on cleanups.
=> Valgrind fixes

plugins/python/redisgears_python.c, pytest/common.py, pytest/includes.py, pytest/test_async.py, pytest/test_basics.py, pytest/test_errors.py, pytest/test_profile.py, pytest/test_register.py, pytest/test_requirements.py, src/readers/streams_reader.c
Cleanup performed:
1. deleted all registration
2. delete all executions
This should cleanup occasional valgrind failure and in the future will allow us to run the tests with env-reuse flag and speed them up even more.
=> Used python decorator to perform cleanups after tests

plugins/python/redisgears_python.c, src/common.c, src/common.h, src/module.c, src/redisgears.h
This PR is for future compatability to Redis 7. Till Redis 7, if commands would have executed from background thread, then Redis would not have wrap them with multi exec and the commands would not have executed atomically on replica. Gears solved
it by propagating multi exec by itself.
Thanks to this PR: https://github.com/redis/redis/pull/9890 It is no longer needed to replicate multi exec, Redis takes care of this for us.
=> Fix #650, do not propagate multi exec on Redis 7.

src/command_hook.c
The keys value returned from RedisModule_GetCommandKeys was not freed
=> Fix leak on CommandHook_DeclareKeys

plugins/python/cloudpickle.py, plugins/python/redisgears_python.c, pytest/test_basics.py, pytest/test_register.py
The problem
---
After deserialization, the deserialized function are created with its own globals dictionary. We want all the functions on the same execution (and even different execution that was generated by the same `RG.PYEXECUTE` command) to share the same globals dictionary. The current solution is to change the function global dictionary to be the global dictionary of the `PY.EXECUTE` session that created the execution.
This solution only changes the top most function, but it does not change function that is used by it, so the following example will break:
```
g = 1
def f1():
global g
g = g + 1
print(id(globals()))
return g
def f(x):
global g
g = g + 1
print(id(globals()))
return f1()
GB('CommandReader').map(f).register(trigger='test', convertToStr=False) …
```
=> Fix globals dictionary not set correctly after deserialization.

plugins/python/redisgears_python.c, pytest/common.py, pytest/test_async.py, pytest/test_basics.py, src/readers/command_reader.c, src/readers/keys_reader.c
Fix #545, check REDISMODULE_CTX_FLAGS_DENY_BLOCKING flag before blocking the client.
We check it on 3 places and act as if we run in MULTI/EXEC or Lua script:
1. RG.PYEXECUTE
2. Command override
3. Keys Reader commands option
=> Fix #545, check REDISMODULE_CTX_FLAGS_DENY_BLOCKING flag before blocking the client.

src/cluster.c
On a single shard enterprise database, RedisModule_ShardingGetSlotRange will return first and last slot as -1. In this case, set it to 0 (return string that matches the first slot).
=> Fix hashtag() function on enterprise.

pack.sh
The build used to error as below. This locale change should solve that.
```
This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```
=> Locale change, as a result of the build error

plugins/python/redisgears_python.c
Given that we compile for each target OS, on the OS itself, this check should not be present. It limits (for example) the ability to use Oracle8 for Centos8
=> Removing active OS check

pytest/test_register.py, src/readers/streams_reader.c
Fix #761, Fix #760, stream reader fixes to Pause and Unregister
1. Fix stream reader pause to ack after finish processing the current batch.
2. Fix stream reader unregister to stop processing more batches when finished the current batch.
=> Fix #761, Fix #760, stream reader fixes to Pause and Unregister

docs/configuration.md, plugins/python/redisgears_python.c
Fix #764, allow disabling custom python allocator using module argument.
Introduce a new module argument to disable Redis custom python allocator. The new module argument called `OverridePythonAllocators` and can be set to either `1` or `0`. Disabling custom python allocator allows to achieve better performance (in some cases we saw improvement of up to 50%), the disadvantage is that the report of `RG.PYSTATS` command becomes invalid and Redis will not be able to track and report the memory usage used by the python interpreter.
=> Fix #764, allow disabling costume python allocator using module argument.

plugins/python/redisgears_python.c, src/commands.c, src/execution_plan.c, src/execution_plan.h, src/module.c, src/redisgears.h
Requirement installation was moved to be part of the session update processes, we need to allow the upgrade processes to continue long enough without a timeout. This PR changes the code to use `PythonInstallReqMaxIdleTime` config value to set the session update MaxIdle time.
=> Fix flaky tests by adding MaxIdle time to register session.

pytest/test_register.py, src/readers/streams_reader.c
Fix #791, stop trigger execution on Pause even on failure.
If registration was repeatedly fails, pause would have return OK but would not actually stop triggering executions.
The PR fixes it by checking on 2 locations:
1. On the Pause callback itself. Allow pausing even if registration is in error state.
2. When execution finishes and failed, if the registration is pause avoid triggering another execution.
=> Fix #791, stop trigger execution on Pause even on failure.

pytest/test_register.py, src/readers/streams_reader.c
Fix #792, trigger execution infinitely when trimming is disabled.
When trimming is disabled, if the registration was registered on a stream such that gears consumer group are not point to the beginning of the stream, RedisGears would enter a state where it triggers execution infinitely. Such situation can happened when upgrade a registrations (that has trimming disable) or when loading from RDB (again when trimming disabled).
This happened because RedisGears decides to trigger executions base on the amount of pending data which is calculated by checking the stream length. This check is wrong when trimming is disabled because the stream length is not a good indication to the amount of pending data.
To solve this issue, RedisGears will use a different way to decide if there is more data to …
=> Fix #792, trigger execution infinitely when trimming is disabled.

pytest/run_tests.sh, pytest/test_requirements.py
RedisGraph is a big python library which takes time to install. Replacing it with redis for faster and more stable tests. In addition, increased ExecutionMaxIdleTime to get better stability of tests that installs dependencies.
=> Remove RedisGraph from tests

pytest/run_tests.sh, pytest/test_requirements.py
Return global ExecutionMaxIdleTime as other tests need it. Increase timeout for unstable replication test.
=> Return global ExecutionMaxIdleTime as other tests need it.

pytest/test_sessions.py, src/readers/command_reader.c
The invalid memory access happened because each registration was examine even if its not a command reader. This causes wrong casting of structs and in rare cases invalid memory access and crash.
=> Fix MOD82576, fix invalid memory access when checking if a trigger is already register

.circleci/config.yml, plugins/jvmplugin/pytest/test_register.py, pytest/common.py, pytest/test_register.py, src/cluster.c
Fix #817. Change refresh cluster to be compatible with Redis 7.
Additional changes:
* Fix tests to be compatible with Redis 7.
* Run with enableDebugCommand on Redis 7.
* Do not crash on info collection on test failure.
=> Redis 7 fixes

pytests/common.py, pytests/test_cluster.py
Extract relevant information on test failure.
The information extracted are:
1. `info everything` from each shard.
2. Shards logs.
This information will be printed as forced debug print so we will see it on CI.
=> Extracto information on failure

.github/wordlist.txt, .github/workflows/CENTOS_7_REUSABLE.yml, .github/workflows/CENTOS_8_REUSABLE.yml, .github/workflows/MACOS_REUSABLE.yml, .github/workflows/UBUNTU_BIONIC_REUSABLE.yml, .github/workflows/UBUNTU_FOCAL_REUSABLE.yml, .github/workflows/msrv.yml, docs/function_advance_topics.md, pytests/test_basics.py, redisgears_core/src/function_list_command.rs, redisgears_core/src/lib.rs, redisgears_v8_plugin/Cargo.toml, redisgears_v8_plugin/src/v8_function_ctx.rs, redisgears_v8_plugin/src/v8_native_functions.rs
Fix #894 
The PR adds support for RESP3 on 2 commands:
1. RG.FUNCTION LIST will now return the data in RESP3 (if requested by the client). This means that all the information will be presented as map instead of array and will be easier for the user to understand.
2. RG.FCALL will return the data in RESP3 (if requested by the client). Sense RG.FCALL runs user code, we define the following rules to translate the return value from  the user code into RESP types:
| JS type                                                          | RESP2         | RESP3                                  |
|------------------------------------------------------------------|---------------|----------------------------------------|
| `string`                                                         | `bulk string` …
=> Resp3 support

pytests/common.py
Redis do not update the client `woff` (Last write global replication offset) value if the command went to the background and the replicate operation happened from the background. This cause the `wait` command to be ineffective.
By sending a simple command that replicated to the replica (like `publish`)(before the `wait` command), We make sure the client `woff` value will be updated correctly and the `wait` command will be executed as expected.
In addition this change make sure that connection that did not register the library will also wait for the library to reach the replica (`wait` command waits for all the write that was performed by the current connection).
This should fix failures such as: https://github.com/RedisGears/RedisGears/actions/runs/4870846502/jobs/8687088127
We should …
=> Fix flaky tests.

Cargo.toml, redisgears_macros_internals/Cargo.toml, redisgears_macros_internals/src/allow_deny_lists.rs, redisgears_macros_internals/src/lib.rs, redisgears_v8_plugin/Cargo.toml, redisgears_v8_plugin/src/v8_backend.rs
Fix #902 add allow list and deny list to filter JS globals.
Any global which are not on the allow list will be removed. If the global is also not appear of the deny list, we will output a log message indicating we have a global which we do not considered and we should check the porpose of this global and decide if we want to filter it or not.
List of allow globals:
* Object
* Function
* Array
* Number
* parseFloat
* parseInt
* Infinity
* NaN
* undefined
* Boolean
* String
* Symbol
* Date
* Promise
* RegExp
* Error
* AggregateError
* RangeError
* ReferenceError
* SyntaxError
* TypeError
* URIError
* globalThis
* JSON
* Math
* Intl
* ArrayBuffer
* Uint8Array
* Int8Array
* Uint16Array
* Int16Array
* Uint32Array
* Int32Array
* Float32Array
* Float64Array
* Uint8ClampedArray
* BigUint64Array
* …
=> Add allow list to filter out globals.

.github/wordlist.txt, docs/cluster_support.md, docs/commands.md, docs/sync_and_async_run.md, pytests/test_acl.py, pytests/test_basics.py, pytests/test_cluster.py, pytests/test_errors.py, pytests/test_notifications_consumers.py, pytests/test_stream_reader.py, pytests/test_verbose_error_reporting.py, ramp.yml, redisgears_core/src/function_del_command.rs, redisgears_core/src/function_list_command.rs, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs, redisgears_core/src/run_ctx.rs, redisgears_plugin_api/src/redisgears_plugin_api/function_ctx.rs, redisgears_plugin_api/src/redisgears_plugin_api/load_library_ctx.rs, redisgears_v8_plugin/src/v8_function_ctx.rs, redisgears_v8_plugin/src/v8_native_functions.rs
Added `RG.FCALLASYNC` to run asynchronous functions.
Solved: https://github.com/RedisGears/RedisGears/pull/895
The PR adds a new command `RG.FCALLASYNC`. Run asynchronous functions can only be done using this new command. Trying to run asynchronous functions using `RG.FCALL` will fail with an error.
In addition, the PR introduce a new `JS` api, `redis.register_async_function` which is the same as `redis.register_function` but also accept async function (coroutine). Trying to register async function using `redis.register_function` will fail with an error.
Require: https://github.com/RedisLabsModules/redismodule-rs/pull/326
=> Introduce register_async_function API.

docs/configuration.md, pytests/test_basics.py, redisgears_core/Cargo.toml, redisgears_core/src/compiled_library_api.rs, redisgears_core/src/config.rs, redisgears_core/src/lib.rs, redisgears_plugin_api/src/redisgears_plugin_api/backend_ctx.rs, redisgears_v8_plugin/src/v8_backend.rs, redisgears_v8_plugin/src/v8_function_ctx.rs, redisgears_v8_plugin/src/v8_native_functions.rs, redisgears_v8_plugin/src/v8_notifications_ctx.rs, redisgears_v8_plugin/src/v8_redisai.rs, redisgears_v8_plugin/src/v8_script_ctx.rs, redisgears_v8_plugin/src/v8_stream_ctx.rs
V8 allows to limit the memory usage of a single isolates. Unfortunately, RedisGears uses multiple isolates and so increasing the memory usage of each isolate separately is not good enough. We want to limit a total memory usage of all the isolates. The following PR attempt to do so.
The idea is to start each isolate with a respectively small memory usage (few MB), and slowly increase the limit once reach while checking that we are not increasing to much and bypass the total limit.
The PR introduces 4 new configuration values:
1. `v8-maxmemory` - the total memory limit allowed to be used by all the open isolates, default 200MB.
2. `v8-library-initial-memory-usage` - the initial memory given to a new isolate, default 2MB.
3. `v8-library-initial-memory-limit` - the initial limit given to an …
=> Maxmemory support for total V8 isolates.

.github/wordlist.txt, docs/databse_triggers.md, pytests/test_notifications_consumers.py, redisai_rs/Cargo.toml, redisgears_core/Cargo.toml, redisgears_core/src/keys_notifications_ctx.rs, redisgears_core/src/lib.rs, redisgears_plugin_api/Cargo.toml, redisgears_plugin_api/src/redisgears_plugin_api/keys_notifications_consumer_ctx.rs, redisgears_v8_plugin/Cargo.toml, redisgears_v8_plugin/src/v8_native_functions.rs, redisgears_v8_plugin/src/v8_notifications_ctx.rs
Fix #896.
The PR adds a new optional argument, `onTriggerFired`, that allows specify a function that will be invoke exactly when a notification happened and allows to read the data as it was at the time of the notification.
In addition, the PR refactor the API to use Redis post notification job where it is safe to perform write operations.
Example of the new API usage was added to the docs: https://github.com/RedisGears/RedisGears/blob/74af30b35c223e4589dfe878fe1c3af0a9d55d03/docs/databse_triggers.md#advance-usage
=> Added optional `onTriggerFired` argument to notification consumer API.

pytests/test_cluster.py, redisgears_core/src/rdb.rs, redisgears_v8_plugin/src/v8_backend.rs
Fixes #934.
Use AUX save V2 so if the user do not use RedisGears he will be able to load the RDB even if RedisGears module is not loaded.
=> Use AUX save V2.

pytests/test_basics.py, redisgears_v8_plugin/src/v8_backend.rs
By calling `calc_isolates_used_memory` we will check the exact memory usage of all isolate instead of the estimated value used on `bypass_memory_limit`. Without it, one can create a lot of libraries and bypass the OOM value as long as each single library will not bypass the isolate OOM.
=> Force OOM on function load

README.md, docs/commands.md, docs/create_development_environment.md, docs/function_advance_topics.md, docs/sync_and_async_run.md, pytests/common.py, pytests/test_acl.py, pytests/test_basics.py, pytests/test_cluster.py, pytests/test_errors.py, pytests/test_notifications_consumers.py, pytests/test_stream_reader.py, pytests/test_verbose_error_reporting.py, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs, tests/benchmarks/rg_fcall_async.yml, tests/benchmarks/rg_fcall_redis_cmd.yml, tests/benchmarks/rg_fcall_redis_cmd_async.yml, tests/benchmarks/rg_fcall_simple.yml, tests/benchmarks/rg_sync_and_async.yml
Fixes #920.
The PR combine the library and the function name to a single, `.` seperated argument instead of 2 distinct arguments. The main goal is to make the API closer to Redis Function while not giving up on the library name which we believe is important.
The PR also forces the set of allowed char for functions and library name to be `[a-zA-Z0-9_][a-zA-Z0-9_]?` just like Redis Function.
=> Combine library and function name to a single argument.

.github/workflows/nightly-benchmark.yml
- CP of https://github.com/RedisGears/RedisGears/pull/956 
- Normally I wait for it to be merged but given I need v2.0 performance data I've went ahead and created this PR and triggered the benchmarks
=> CP v2.0: Runnning benchmarks on pushes to master. Enabling nightly on 2.0 branch

pytests/test_basics.py, redisgears_v8_plugin/src/v8_native_functions.rs
The code were missing a call to `before_run` and `after_run` which causes RedisGears to miss the fact that the isolate runs JS code. This cause it not to monitor the code for timeout.
=> Added missing before_run and after_run calls so that timeout will work properly

pytests/common.py
Recent changes of LibMR is lazy initialisation of threads and connections. So we can not wait for the connections to the other shards to be `connected`. Instead we can wait for it to be either `connected` or `uninitialised` (Which means that we got the topology and we will connect when needed).
=> Fixes according to recent librm changes

pytests/common.py, redisgears_core/src/config.rs, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs, redisgears_v8_plugin/src/v8_backend.rs
The PR allow to postpone the opening of new threads up until the time we really need them. In addition, the PR postpone the loading of the V8 plugin up until the time we really need it to run JS code.
Those changes reduce Gears footprints if its not used and reduce the risk of damaging existing servers that do not use RedisGears (but do load it).
=> Allow lazy loading of V8 engine and threads.

pytests/common.py, pytests/test_basics.py, pytests/test_stream_reader.py, redisgears_core/src/lib.rs, redisgears_v8_plugin/Cargo.toml, redisgears_v8_plugin/src/v8_backend.rs, redisgears_v8_plugin/src/v8_function_ctx.rs, redisgears_v8_plugin/src/v8_native_functions.rs, redisgears_v8_plugin/src/v8_notifications_ctx.rs, redisgears_v8_plugin/src/v8_redisai.rs, redisgears_v8_plugin/src/v8_script_ctx.rs, redisgears_v8_plugin/src/v8_stream_ctx.rs
The pull request (PR) introduces support for handling fatal errors in async functions. One of the primary challenges with async functions and fatal errors is that the callback set on the async function's future object will not be invoked if the async function encounters a fatal error, such as a timeout or an out-of-memory (OOM) condition. In such cases, the only way to resolve the promise is by registering a callback that will be triggered when the promise object is garbage collected. This is when an error can be returned to the user.
The PR also includes a comprehensive rearrangement of the JavaScript (JS) code invocation and promise handling. This is achieved through three key code refactoring steps:
1. Any invocation of JS code is performed using the `script_ctx` object, which utilizes …
=> Add Support for Handling Fatal Errors in Async Functions

redisgears_v8_plugin/src/v8_script_ctx.rs
The PR fixes compilation issue according to recent V8-rs changes that require native functions to live for the 'static lifetime: https://github.com/RedisGears/v8-rs/pull/41
=> Added 'static lifetime to promise OnDone closure.

docs/functions.md, plugins/jvmplugin/gears_runtime/pom.xml, plugins/python/redisgears_python.c, pytest/test_basics.py, src/execution_plan.c
The PR add `mode` parameter to run function that can be one of the following:
* **'async'**: execution will be asynchronous across the entire cluster
* **'async_local'**: execution will be asynchronous and restricted to the handling shard
In addition, the PR updates the jackson dependency on jvm plugin to 2.15.2.
=> Added execution mode parameter run `run` function.

.github/workflows/branch_merge-benchmark.yml, .github/workflows/nightly-benchmark-v8-plugin-main.yml
- Runs benchmarks on merges to master/version branches using the stable v8 
- Runs nightly with v8 main version. To distinguish between v8 main and stable we're adding a suffix -v8-main to the branch name.
=> Running benchmarks with different v8 engines on nightly/merges to branches

.github/workflows/branch_merge-benchmark.yml, .github/workflows/nightly-benchmark-v8-plugin-main.yml, .github/workflows/trigger-benchmark.yml, dockerbuilds/build_and_test.incl, redisgears_core/src/lib.rs, redisgears_plugin_api/src/redisgears_plugin_api/backend_ctx.rs, redisgears_v8_plugin/src/v8_backend.rs
The crash started to happened since we merge this PR: https://github.com/RedisGears/RedisGears/pull/973
The purpose of the PR was to initialise the V8 backend lazy only when needed. A side effect was that the V8 might have been initialises on some other thread which are not the main thread. Unfortunately, the V8 platform must be initialised on the main thread (for some reason that I yet been able to understand) and this causes the crash.
The fix is to perform minimal initialisation steps on load time and leave the heavy V8 initialisation processes for the first time its been used. To achieve this, the PR adds a new `on_load` backend interface to `V8Backend` that will be called on loading time and allow the V8 backend to only initialise the platforms.
Depends on: …
=> Fix crash on benchmark when running with V8 main branch.

pytests/test_stream_reader.py, redisgears_core/src/lib.rs
Fix #1000.
Trim the stream should be done on post execution job so we will make sure the trimming happeneds last. otherwise, we might perform the trimming on the key notification itself and this is not allow (we can not perform any write operation inside a key space notification callback, doing so can cause issues like replication reordering).
=> Fix #1000, trim stream on post execution job.

redisgears_core/src/lib.rs
Create a redis string not attached to context so we will not access a freed context when free the RedisString.
=> Create a redis string not attached to context

pytests/test_notifications_consumers.py, redisgears_core/src/lib.rs
Fix #1005.
If a function trigger a stream processing by writing into a stream, when the stream processing code were done it would have reset the `NotificationBlocker` and so it would trigger notifications inside the function code.
To avoid that, the notification blocker will reset the value to the previous value that was set before.
=> Fix #1005, avoid trigger key space notification inside function that trigger stream processing

pytests/test_stream_reader.py, redisgears_core/src/lib.rs, redisgears_core/src/stream_reader.rs
Currently Stream trigger is invoke as part of the stream key space notification. One of Redis restrictions is that a module should not perform any write operation inside a key space notification callback. The PR moves the stream trigger invocation into a post notifications job so we will not violate the restriction. Without this fix we are getting a reordering of the replication order (the `xadd` command are replicated last).
=> Run stream trigger on post notificaiton job.

.github/workflows/pull_request.yml, docs/build_instructions.md, docs/docs/Configuration.md, pytests/test_basics.py, redisgears_core/src/config.rs, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs
The loading timeout introduce on https://github.com/RedisGears/RedisGears/pull/999 should also be applied when loading data from AOF and when replica gets the replication stream from its primary. To handle those cases, set the loading timeout to apply also on `_rg_internals.function load` command (which is the command that is written to AOF and sent on the replication stream).
In addition, the PR rename `rdb-lock-redis-timeout` to `db-loading-lock-redis-timeout` so it will match also to AOF and not only RDB.
In addition, the PR makes sure that `_rg_internals.function load` is only invoked on replica or during loading time.
=> Apply loading timeout on AOF and Replication stream.

docs/docs/_index.md
If we render the markdown on redis.io, then the title would appear twice because it's pulled in from the meta data header. So I am removing this title here.
=> Fixes title

pytests/test_stream_reader.py, redisgears_core/src/lib.rs, redisgears_core/src/stream_reader.rs
Today the post notification job is created after the stream data was read. This is wrong because it means that we will read the data on the notification itself. Moving the post notification job into `on_stream_touched` will make sure the entire logic is happening inside the post notification job.
=> Move the post notification job creation into `on_stream_touched`.

pytests/test_errors.py, pytests/test_stream_reader.py, ramp.yml, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs
The PR fixes `_rg_internals.update_stream_last_read_id` command definition with respect to key spec. Though the command is internal, it is send to replica (and replica of) and it is required that the command definition will be done correctly.
In addition, the PR makes sure that all internal command will only run if came from primary. Tests was added to verify it.
Last, the PR removes `_rg_internals.update_stream_last_read_id` from the `exclude_commands` command section of ramp.yml. We need this command to not be excluded so that if it is sent on replica of, it will arrive successfully to the destination.
=> Fix `_rg_internals.update_stream_last_read_id` command definition.

docs/docs/Quick_Start_CLI.md
We have many existing links referring to 
the `https://redis.io/docs/interact/programmability/triggers-and-functions/quick_start` URL witch now throws 404. 
@dwdougherty @thomascaudron
=> Add missing alias for Quick_Start_CLI.md

.circleci/config.yml, redisgears_v8_plugin/src/v8_backend.rs
The Iterator was added on v8 version 11.7. Seems like it is safe to add it to the allow list:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator
@vityafx @leibale let me know what you think.
=> Added Iterator global to allow list

Cargo.toml, redisai_rs/Cargo.toml, redisgears_core/Cargo.toml, redisgears_core/src/lib.rs, redisgears_plugin_api/Cargo.toml, redisgears_v8_plugin/Cargo.toml
In addition, the PR move the redis-module dependency to be defined on the entire workspace so it will be easier to change it globally (when debugging locally for example).
Notice: the `ProxyFiltered` require [this PR](https://github.com/RedisLabsModules/redismodule-rs/pull/369) to function correctly
=> Added ProxyFiltered flag to internal commands

redisgears_core/src/function_del_command.rs, redisgears_core/src/function_load_command.rs, redisgears_core/src/lib.rs
The PR makes 3 small fixes for replicaof:
1. When loading a library always replace an existing library (if exists). This is mainly because we prefer to listen to the primary and if it gives us a library to load we do it.
2. When deleting a library on replica we always return an OK reply even if the library does not exists. If we return an error we will break the replication stream and we do not want to do that in case we were asked to delete a none existing library.
3. If the `_rg_internals.function` command were done successfully, we replicate it (in case we have another replica connected to us).
=> Small Replicaof fixes

Cargo.toml
According to the following [link](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions) we need to specify the resolver to use in order to avoid a warning on compilation time:
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
According to [this](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) and base on the changes …
=> Specify resolver for workspace

redisgears_v8_plugin/src/v8_backend.rs
On https://github.com/RedisGears/RedisGears/commit/8b8c91b6fbd15b50bb5c166c602334b5fac37fd2 we added the `Iterator` to the allow list. Its wrong to do it on a patch version because old 2.0 version might not be able to load RDB that was created by some newer 2.0.x version. It is better to put the `Iterator` on the deny list for patches versions on 2.0.
=> Move `Iterator`  to deny_list

docs/docs/Development.md
Updates to the Development page that describe how to use a third-party package with a Redis Stack function.
=> DOC-2832: add 3rd-party package info to Development page

.github/workflows/pull_request.yml, examples/js_package/index.js, examples/js_package/package.json, js_api/deploy.js, pytests/common.py, pytests/test_debugging.py, redisgears_core/Cargo.toml, redisgears_core/src/compiled_library_api.rs, redisgears_core/src/config.rs, redisgears_core/src/debugging.rs, redisgears_core/src/function_load_command.rs, redisgears_core/src/keys_notifications.rs, redisgears_core/src/lib.rs, redisgears_core/src/rdb.rs, redisgears_core/src/stream_reader.rs, redisgears_core/src/stream_run_ctx.rs, redisgears_plugin_api/Cargo.toml, redisgears_plugin_api/src/redisgears_plugin_api/backend_ctx.rs, redisgears_plugin_api/src/redisgears_plugin_api/load_library_ctx.rs, redisgears_plugin_api/src/redisgears_plugin_api/mod.rs, redisgears_v8_plugin/Cargo.toml, redisgears_v8_plugin/src/v8_backend.rs, redisgears_v8_plugin/src/v8_function_ctx.rs, redisgears_v8_plugin/src/v8_native_functions.rs, redisgears_v8_plugin/src/v8_notifications_ctx.rs, redisgears_v8_plugin/src/v8_redisai.rs, redisgears_v8_plugin/src/v8_script_ctx.rs, redisgears_v8_plugin/src/v8_stream_ctx.rs
Adds a possibility to debug JavaScript code. To be able to do that, the code must be uploaded to Redis with the "debug" option. Then, in the RESP3 reply, there will be connection hints reported, describing the ways that one may use in order to connect to the remote debugging server in RedisGears.
The debugging is done in a single thread, piece by piece. In the code, it is expressed by working in the cron job so that if nothing is happening with the user script, the thread isn't blocked, and any other work can be performed. However, if the user script is paused, either due to a breakpoint or for whatever other reason, this thread is blocked, waiting until the user unpauses the script. This also provides an atomicity guarantee so that if a script is paused under debugging, nothing else can …
=> Add JavaScript debugging

Cargo.toml, Dockerfile, deny.toml, dockerbuilds/build_and_test.incl, redisai_rs/Cargo.toml, redisgears_core/Cargo.toml, redisgears_macros_internals/Cargo.toml, redisgears_plugin_api/Cargo.toml, redisgears_v8_plugin/Cargo.toml
This allows to:
1. Check for the license compatibility among all the dependencies.
2. Check for the binaries included within the source code of the crates.
=> Add cargo-deny configuration.

tests/benchmarks/defaults.yml, tests/benchmarks/rg_fcall_async.yml, tests/benchmarks/rg_fcall_redis_cmd.yml, tests/benchmarks/rg_fcall_redis_cmd_async.yml, tests/benchmarks/rg_fcall_simple.yml, tests/benchmarks/rg_keyspace_async_simple.yml, tests/benchmarks/rg_keyspace_baseline.yml, tests/benchmarks/rg_keyspace_sync.yml, tests/benchmarks/rg_keyspace_sync_simple.yml, tests/benchmarks/rg_stream_baseline.yml, tests/benchmarks/rg_stream_process_async.yml, tests/benchmarks/rg_stream_process_empty_async.yml, tests/benchmarks/rg_stream_process_empty_sync.yml, tests/benchmarks/rg_stream_process_sync.yml, tests/benchmarks/rg_sync_and_async.yml
This PR enables spot instance deployments as a 1st deployment option. If it fails it uses the default non spot deployment in an agnostic manner to the developer/CI runner.
=> Enabled SPOT Instance deployments on CI benchmarks

redisgears_core/src/background_run_scope_guard.rs
The issue is that the `detached_ctx_guard` was released before the `_notification_blocker`. This cause the Redis lock to be released before the notification was resumed. If a notification would have arrive in between the time the Redis lock was released to the time the notifications was resumed, we would have lost it.
=> Fix issue where ksn might be ignored

redisgears_core/src/background_run_scope_guard.rs
The issue is that the detached_ctx_guard was released before the _notification_blocker. This cause the Redis lock to be released before the notification was resumed. If a notification would have arrive in between the time the Redis lock was released to the time the notifications was resumed, we would have lost it.
(cherry picked from commit e5c9a5e7e57f43db633c5fb9503f9a64a5f8dc18)
=> Fix issue where ksn might be ignored (#1067)

.github/workflows/branch_merge-benchmark.yml, .github/workflows/trigger-benchmark.yml
CP of https://github.com/RedisGears/RedisGears/pull/1070
=> [CP 2.0] Fixed rg_keyspace_async_simple benchmark by specifying a larger v8-maxmemory

.github/workflows/branch_merge-benchmark.yml, .github/workflows/trigger-benchmark.yml
- Fixes the failures in https://github.com/RedisGears/RedisGears/actions/runs/7198768949/job/19776796580
=> Fixed rg_keyspace_async_simple benchmark by specifying a larger v8-maxmemory

pytests/test_basics.py, redisgears_v8_plugin/src/v8_backend.rs, redisgears_v8_plugin/src/v8_native_functions.rs
Turns out it is not allowed to raise a termination exception on a co-routine, and as of v12.1 V8 asserts it. To fix the issue we catch the timeout error (termination exception) on `block` function and raise a regular none termination exception. This means that the user will now be able to catch timeout error on the co-routine code and handle it. Currently we do not force any timeout on co-routine so this change does not allow the user to do anything he could not yet already do.
successful nightly run: https://github.com/RedisGears/RedisGears/actions/runs/7491877476
=> Fix nightly run failure

pytests/test_basics.py, redisgears_v8_plugin/src/v8_native_functions.rs
Turns out it is not allowed to raise a termination exception on a co-routine, and as of v12.1 V8 asserts it. To fix the issue we catch the timeout error (termination exception) on `block` function and raise a regular none termination exception. This means that the user will now be able to catch timeout error on the co-routine code and handle it. Currently we do not force any timeout on co-routine so this change does not allow the user to do anything he could not yet already do. successful nightly run: https://github.com/RedisGears/RedisGears/actions/runs/7491877476
(cherry picked from commit 0d1add66c46c4775e85c07295c66d83e1c48274a)
=> Fix nightly run failure (#1077)

redisgears_core/build.rs
The other modules now use aarch64 throughout. This PR removes the change to rename as arm64v8 and resettles on aarch64 and provided by the OS. This is needed by redis-stack
(cherry picked from commit cb9d4d3d58064768bc66a37f7e7fb1af16480207)
=> aligning arm64v8 with aarch64, as elsewhere (#1044)

.github/workflows/pull_request.yml, docs/build_instructions.md, pytests/test_basics.py, redisgears_core/Cargo.toml, redisgears_v8_plugin/src/v8_native_functions.rs
When log NULL char, the server crashed on panic on redismodule-rs when trying to convert the `&str` to `CString`:
https://github.com/RedisLabsModules/redismodule-rs/blob/bf2b3a6a04b795ad1d58d5252ae22d25430c3349/src/logging.rs#L55
When we create our logs we can be sure we do not have embedded NULLs inside the log message, but when the log message comes from user script we can not be sure. To solve it we escape the string using `escape_default` which will escape all chars according to the following rules:
* Tab is escaped as `\t`.
* Carriage return is escaped as `\r`.
* Line feed is escaped as `\n`.
* Single quote is escaped as `\'`.
* Double quote is escaped as `\"`.
* Backslash is escaped as `\\`.
* Any character in the 'printable ASCII' range `0x20` .. `0x7e` inclusive is not escaped.
* …
=> Fix crash when logging NULL chars.

pytests/test_basics.py, redisgears_v8_plugin/src/v8_native_functions.rs
When log NULL char, the server crashed on panic on redismodule-rs when trying to convert the `&str` to `CString`:
https://github.com/RedisLabsModules/redismodule-rs/blob/bf2b3a6a04b795ad1d58d5252ae22d25430c3349/src/logging.rs#L55
When we create our logs we can be sure we do not have embedded NULLs inside the log message, but when the log message comes from user script we can not be sure. To solve it we escape the string using `escape_default` which will escape all chars according to the following rules:
* Tab is escaped as `\t`.
* Carriage return is escaped as `\r`.
* Line feed is escaped as `\n`.
* Single quote is escaped as `\'`.
* Double quote is escaped as `\"`.
* Backslash is escaped as `\\`.
* Any character in the 'printable ASCII' range `0x20` .. `0x7e` inclusive is not escaped.
* …
=> Fix crash when logging NULL chars. (#1093)

pytest/test_requirements.py
Fix valgrind failure: https://app.circleci.com/pipelines/github/RedisGears/RedisGears/4906/workflows/714ed9f4-4249-449c-bcbe-249a9a424fb8/jobs/13503?invite=true#step-111-50461_75
The failure happened because after restart (`env.dumpAndReload(restart=True)`) the value for `cluster-node-timeout` is set to default. Resetting it right after the restart should fix the failure we get (`CLUSTERDOWN The cluster is down`)
=> Fix valgrind failure

src/readers/command_reader.c, src/readers/keys_reader.c, src/readers/streams_reader.c, src/utils/thpool.c
The PR introduce 2 changes:
1. Clear last error once an execution was finished successfully.
2. On error/unregister/unpaus, clear a not yet started executions.
=> Clear last error after successful run

pytest/test_register.py, src/common.c
The issue only happened after bypass ID of 128. The issue is that we first got the a byte of the id buffer and then cast it to long long, while the intention was to take 8 bytes of the ID buffer and then cast them to long long.
=> Fix issue where generated ID got lower value after reload from RDB
