RedisGears/RedisGears

src/redisgears_python.c

As coded during RedisConf19
Signed-off-by: Itamar Haber <itamar@redislabs.com>

Fixes model runner

---

Dockerfile

Signed-off-by: Itamar Haber <itamar@redislabs.com>

Uses redis:latest in Dockerfile

---

Dockerfile

Signed-off-by: Itamar Haber <itamar@redislabs.com>

Moves Dockerfile runner to latest redis

---

docs/quickstart.md
src/config.c

And also removes dead code that breaks compilation w/ clang
Signed-off-by: Itamar Haber <itamar@redislabs.com>

Adds OSX deps to README

---

leakcheck.supp
pytest/test_basics.py
src/GearsBuilder.py
src/execution_plan.c
src/execution_plan.h
src/keys_reader.c
src/keys_reader.h
src/lock_handler.c
src/mgmt.c
src/mgmt.h
src/module.c
src/redisgears.h
src/redisgears_python.c
src/redisgears_python.h
src/streams_reader.c
src/streams_reader.h
src/utils/dict.c
src/utils/dict.h

document the new commands will be done before releasing next version

Register execution management

---

system-setup.py

Added packages for Python dependencies

---

Dockerfile
ramp.yml

Also added code in Dockerfile to package retreival from a container.

RAMP: min_redis_pack_version to 5.4

---

build/cpython/Makefile
build/cpython/bind-pyenv
build/cpython/clean-pyenv
build/cpython/fix-pyenv
build/cpython/install-pyenv
build/cpython/prepare-python
build/cpython/pyenv-relink
build/platforms/Makefile
deps/readies/bin/getpy2
deps/readies/bin/platform
deps/readies/paella/platform.py
deps/readies/paella/setup.py
pack.sh

* Fixes for 'make all' malfunctions
* Setting up pyenv under bindir and placing a symlink in /opt/redislabs
* Fixes for symlinks in pyenv leading in the wrong direction
* build/platforms: copying artifacts from containers into artifacts directory

Yet another build system refactoring

---

deps/readies/paella/setup.py

New pip is 20.0 and it's breaking stuff.

Fixed pip to version 19.3.1

---

docs/quickstart.md

Small doc changes

---

.circleci/config.yml
docs/requirements.txt
docs/theme/css/versions-menu.css
docs/theme/javascript/versions-menu.js
docs/theme/main.html
mkdocs.yml

This PR adds versioned documentation.

[WIP] Adds versioned docs

---

docs/snippets/intro/intro-003.py

Minor fix for expected result

---

docs/snippets/intro/intro-005.py

Rick is 70 and Morty is 14 therefore = 84

Minor fix to expected result

---

docs/intro.md

Fix typo in intro.md

---

.circleci/config.yml

In the future, I will change it run with the current redisgears but for now this will fix the doc build failure.

fix doc build

---

docs/intro.md

Following the explanation, steps after teps, there is one inconsistency in the doc about a result that is supposed to be returned (based on the datas added).

Fix inconsistency in sample's result supposed to be returned

---

src/common.c
src/common.h
src/module.c
src/readers/command_reader.c
src/readers/keys_reader.c
src/readers/streams_reader.c
src/redisai.h
src/redisgears_python.c
src/redismodule.h

fixes to work with RedisAI

---

src/config.c

downloadDeps -> foreceDownloadDepsOnEnterprise

Fix GearsConfig_ForceDownloadDepsOnEnterprise()

---

Dockerfile
getos.py

This was removed by mistake in the docker image compaction PR.

Dockerfile: install git to allow fetching of requirements

---

pytest/test_basics.py
src/redisgears_python.c

added bytes and bytearray argument to execute command. script returns list of tensors

patched script run and execut command

---

src/redisai.h
src/redisgears_python.c
src/utils/arr.h

added AI API:
1. Tensor get/set from keyspace - without the need to use rm_call
2. variadic input for scripts
Tested on demo

ai API modifications

---

docs/commands.md

Fix RG.PYEXECUTE UNBLOCKING docs

---

pytest/test_network.py
src/cluster.c

* Fix #427, resend pending messages after getting RG.HELLO reply for the first time.
* review fixes

Fix #427, resend pending messages after getting RG.HELLO reply for the first time. (#429)

---

README.md
docs/index.md

Discord link

---

docs/quickstart.md

Fixed a couple of spelling errors, slightly rephrases the sentence containing them.

Fixed a couple of spelling errors and minor rephrasing of one sentence.

---

pytest/test_register.py
src/readers/streams_reader.c

(cherry picked from commit f7523702c5e302c8453f4f1de8b9e627d3145938)

Fix crash on stream reader when stream are dropped while processed.

---

pytest/test_requirements.py
src/redisgears_python.c

Also, fixed requirments -> requirements, and fixed the spec that checks the error message

Fixed spelling and grammar in error returned when passing incorrect arguments to pyexecute

---

src/redisai.h
src/redisgears_python.c

+move ownership of PyTorchScriptRunner after calling scriptRunnerRun/async.

Support running RediaAI torch script async 

---

pytest/common.py
pytest/test_basics.py
pytest/test_errors.py
pytest/test_network.py
src/cluster.c
src/redisgears_python.c

Crash fixes

---

pytest/test_network.py
src/cluster.c

Fix crash on client that send cluster set and disconnect

---

system-setup.py

output="on_error" rather than output_on_error="True"

fixing the build output.

---

plugins/python/redisgears_python.c

Decrease ref count of value after appending it to list

Fix leak in redisAI.tensorToFlatList method

---

system-setup.py

This is not yet wired up to CI

adding gmake4 to centos7 for RedisGears

---

docs/clients.md

(cherry picked from commit 0c3081a4d29dc3c9192e0f256319cb00396a225a)

Update clients.md (#485)

---

plugins/python/redisgears_python.c
pytest/test_basics.py
src/execution_plan.c
src/execution_plan.h
src/module.c
src/readers/command_reader.c
src/redisgears.h

see #586, use RM_BlockedClientMeasureTimeStart and RM_BlockedClientMeasureTimeEnd on async execution to get slowlog report

---

pytest/test_basics.py
src/readers/streams_reader.c

fix MOD-1676, check reply type instead of assert it

---

pytest/test_basics.py
src/readers/streams_reader.c

(cherry picked from commit 2683130f85fddb9765eb573bf43636cbd8e7ea6f)

fix MOD-1676, check reply type instead of assert it (#609)

---

pytest/test_register.py
src/readers/streams_reader.c

fix issue where stream reader might trigger executions on replica

---

build/cpython/install-pyextras

Adding proper path to python extras

---

pytest/test_errors.py
pytest/test_requirements.py

tests fixes after redispy upgrade

---

docs/commands.md
plugins/python/GearsBuilder.py
plugins/python/redisgears_python.c
pytest/test_profile.py
src/module.c
src/redisgears.h

added python profiler when ProfileExecutions is enabled

---

pytest/test_register.py
src/readers/streams_reader.c

On oss cluster, if cluster is not initialized, read commands will failed and return an error. On stream reader, we assert that we read the stream successfully, such assertion will failed on uninitialized cluster and will cause a crash.
Solution:
1. Before start scaning for streams, wait for cluster to be initialized.
2. '1' is not enough, by the time we find a stream to read the cluster might get uninitialized again. To solve this, if we failed to read the stream we retry after 5 seconds. We retry up to 10 times and than abort.
(cherry picked from commit fb9f1ccdd8f7e29ff2e913b67d10900c00cc302b)

Fix #558, wait for cluster to be initialized when reading stream data(#656)

---

.circleci/config.yml
Makefile
pytest/test_network.py

After merging this https://github.com/RedisLabsModules/RLTest/pull/147 it will be possible to run the tests in parallel but for this to work we need a random port to avoid collisions.

Random port on test nextwork

---

pytest/common.py

Extract the following information of test failure:
1. RG.DUMPREGISTRATIONS
2. RG.DUMPEXECUTIONS
3. info everything
The information will be written to a file on the log directory. File name will be the same as the Redis log file name with a suffix
contains the test name. This will promise that the collected information will be uploaded to the CI and we will be able to analyse it.

Extract more information on test failure

---

.circleci/config.yml
Dockerfile
Makefile
build/docker/Makefile
pack.sh

Changes to circleci to push to s3 everything. Also small cleanup while here.

Fixing artifact s3 push

---

ramp.yml

Also removed unneeded vec sim commands

Update min_redis_pack_version to 6.0.12

---

plugins/jvmplugin/src/gears_jvm.c
pytest/test_sessions.py
src/execution_plan.c

* fix missing JVM_SessionDup
* do not failed upgrade if not finding registration to unregister
* fix valgrind leaks
(cherry picked from commit db3e7f006f08ccd1477a453942a63811dd6feb1c)

fix missing JVM_SessionDup (#707)

---

pytest/common.py

Using RedisGears will cause the execution to appears in different stats. Some tests assumes stats are empty and this cause a failure.

Do not use RedisGears to test registration intergrity.

---

.circleci/config.yml
Dockerfile
Makefile
build/cpython/install-pyextras
pack.sh
plugins/jvmplugin/pack.sh
plugins/jvmplugin/system-setup.py
pytest/test_basics.py
pytest/test_register.py
pytest/test_requirements.py
requirements.txt
system-setup.py

Bullseye fixes *and* sha256 in ramp

---

pytest/test_register.py
src/readers/readers_common.h
src/readers/streams_reader.c

Fix #731, fix -nan value on registration stats

fix -nan value on registration stats

---

.circleci/config.yml
Makefile
build/hiredis/Makefile
pytest/common.py
pytest/generate_tests_cert.sh
pytest/run_tests.sh
pytest/run_tests_tls.sh
pytest/test_network.py
ramp.yml
requirements.txt
src/cluster.c

Require this fix: https://github.com/RedisLabsModules/RLTest/pull/160

Added tls support

---

src/module.c

Fix MOD-3054. On enterprise, if not plugin was specified, automatically load the python plugin.

Fix MOD-3054. On enterprise, if not plugin was specified, automatically load the python plugin.

---

pytest/test_register.py
src/readers/streams_reader.c

1. Fix valgrind invalid memory access.
2. Fix issue where the stream reader will trigger tons of executions on failures when failure policy is set to 'retry'.

StreamReader fixes

---

plugins/python/redisgears_python.c
src/common.c

In addition, point stderr of any shell invocation to stdout so we will have it on the Redis log file.

Fix MOD-1734, use modulesdatadir env var to find the virtual env location.

---

.circleci/config.yml

null circleci config

---

redisgears_v8_plugin/src/v8_backend.rs

This PR is only to match with the changes on: https://github.com/RedisGears/v8-rs/pull/8
We will introduce a loadtime configuration for this value later on.

Set v8 background worker to 1.

---

pytests/test_cluster.py

Error message was recently changed to be more accurate.

Fix tests failure comparing a wrong error message.

---

.github/workflows/UBUNTU_BIONIC_REUSABLE.yml
.github/workflows/UBUNTU_FOCAL_REUSABLE.yml
redisgears_core/build.rs

changes:
focal -> ubuntu20.04
bionic -> ubuntu18.04

Fix ubnutu artifact names.

---

rfcs/2-async-api-refactoring.md

[Rendered](https://github.com/RedisGears/RedisGears/pull/895/files?short_path=d7d1bf2#diff-d7d1bf20e68a1c47c92100d49d1d6aad68a37cbaa4c0f11c3a88826a11d7a861)

RFC for async function API refactoring.

---

.github/workflows/release.yml

Release process fix for path change

---

.circleci/config.yml

- fixing tag on cirlce release
- syntax

CircleCI release regex fix

---

redisgears_core/build.rs

Fix os names for amazon linux 2 and debian 11.

---

.circleci/config.yml
dockerbuilds/dockerfile.debian.tmpl

Due to https://github.com/deadsnakes/issues/issues/251

Fixing deadsnakes bionic issue

---

.circleci/config.yml
redisgears_core/build.rs

Install s3cmd on OSX only. There will be a second push, to remove the force upload, so that we can test this, instead of on merge for once.

Install s3cmd on osx

---

pytests/common.py

Added more information on tests failure:
1. Print the information also on exceptions
2. Print the output of `tfunction list vvv`

More information on tests failures.

---

redisgears_v8_plugin/src/v8_backend.rs

Set panic handler on v8 plugin. The plugin handler will call `RedisModule__Assert` to make sure we get a full crash report on panicking. Notice that we need to set it separately on the V8 plugin because the panic handler is enabled at the scope of an ELF and the V8 plugin is a separate `.so` file (separate ELF file).

Set panic handler on v8 plugin

---

pytests/test_basics.py
redisgears_v8_plugin/src/v8_native_functions.rs

When resolving a promise we turing the resolver persisted value into a local value (`take_local` function). This can only happened once, if happened more then once an assert will be raise. When we resolved a promise more then once we tried to turn the persisted value to local value more then once and raise the assert.
The fix is to wrap the persisted value with an Option and protect this function to be called once at the first time and ignore it on the rest of the times.

Fix crash when resolving the same promise twice.

---

docs/commands/tfcall.md
docs/commands/tfcallasync.md
docs/commands/tfunction-delete.md
docs/commands/tfunction-list.md
docs/commands/tfunction-load.md
docs/docs/_index.md

@thomascaudron Here's the PR for the updated banners (per David M.'s request).

Updating page banners

---

commands.json
docs/docs/_index.md
docs/docs/concepts/Binary_Data.md
docs/docs/concepts/Cluster_Support.md
docs/docs/concepts/Library_Configuration.md
docs/docs/concepts/Sync_Async.md
docs/docs/concepts/triggers/KeySpace_Triggers.md
docs/docs/concepts/triggers/Stream_Triggers.md

Hi Thomas. A couple more fixes related to the redis-stack-website merge. Please merge.

Fix a few broken issues for the T&F merge to redis.io

---

docs/commands/tfcall.md
docs/commands/tfcallasync.md
docs/commands/tfunction-delete.md
docs/commands/tfunction-list.md
docs/commands/tfunction-load.md
docs/docs/Configuration.md
docs/docs/Development.md
docs/docs/Examples.md
docs/docs/Quick_Start.md
docs/docs/_index.md
docs/docs/concepts/Binary_Data.md
docs/docs/concepts/Cluster_Support.md
docs/docs/concepts/JavaScript_API.md
docs/docs/concepts/Library_Configuration.md
docs/docs/concepts/Sync_Async.md
docs/docs/concepts/triggers/KeySpace_Triggers.md
docs/docs/concepts/triggers/Stream_Triggers.md

Thomas - these changes are per David M. (I agree FWIW).

Change all occurrences of Triggers and Functions to sentence case

---

commands.json
docs/commands/tfcall.md
docs/commands/tfcallasync.md
docs/commands/tfunction-delete.md
docs/commands/tfunction-load.md
docs/docs/Configuration.md
docs/docs/Examples.md
docs/docs/Quick_Start.md
docs/docs/_index.md
docs/docs/concepts/Binary_Data.md
docs/docs/concepts/Cluster_Support.md
docs/docs/concepts/JavaScript_API.md
docs/docs/concepts/Library_Configuration.md
docs/docs/concepts/RESP_JS_Conversion.md
docs/docs/concepts/Sync_Async.md
docs/docs/concepts/_index.md
docs/docs/concepts/triggers/KeySpace_Triggers.md
docs/docs/concepts/triggers/Stream_Triggers.md
docs/docs/concepts/triggers/User_Functions.md

This PR is mostly about title case cleanup, but there some other changes as well.

Title case cleanup and sundries

---

.github/workflows/pull_request.yml
dockerbuilds/dockerfile.rhel.tmpl

Build was started to use python3.6 instead of python3.8. Pin it to python 3.8.

Fix rhel8 build

---

docs/docs/Known_Limitations.md

Minor update to the known limitations section.

DOC-2831: update to known limitations section (sandboxed)

---

docs/docs/Debugging.md
docs/docs/Examples.md
docs/docs/Known_Limitations.md
docs/docs/concepts/_index.md

Adding a new debugging information article requested by PM.

DOC-2778: add debugging article

---

Cargo.lock
docs/docs/Debugging.md
docs/docs/Examples.md
docs/docs/Known_Limitations.md
docs/docs/concepts/_index.md
redisgears_core/Cargo.toml
redisgears_v8_plugin/Cargo.toml

The PR also merges documentation changes from master.

Upgrade v8 rs version

---

commands.json

The modules commands, until now did not indicate whether or not they were readonly. This is necessary as it currently impacts a variety of projects.

Updating commands.json

---

dockerbuilds/dockerfile.rhel.tmpl

(cherry picked from commit 5e9844ddf97e75ebf9ab97d6a2e6a95792ef618a)

MOD-6016 link to openssl1.1 on Amazon Linux 2. (#1058)

---

docs/docs/Quick_Start_RI.md

Add RI download/usage info to get started with RI page.
@thomascaudron Please review, approve, and merge.

DOC-3291: add RI download/usage info to get started with RI page

---

.circleci/config.yml

Lifting the change from #1089, for its master branch equivalent

Fixing OSX builds via venv

---

redisgears_core/src/compiled_library_api.rs
redisgears_core/src/function_load_command.rs
redisgears_core/src/lib.rs
redisgears_plugin_api/src/redisgears_plugin_api/backend_ctx.rs
redisgears_v8_plugin/src/v8_backend.rs
redisgears_v8_plugin/src/v8_native_functions.rs

Logs that was writen from scripts will now be written with debug log level when running on enteprise cluster.

Downgrade scripts log level to debug on enterprise cluster.

---

deny.toml

Adds the new windows crate to the ignore list.

Add a recently added target to the ignore list.

---

src/readers/streams_reader.c

The PR changes the use of RM_Call with RM_Scan to avoid lazy expiration during scan operation.

Use RM_Scan instead of RM_Call + scan command to avoid lazy expire
